### ISSUE TITLE
Invalid TOML file /Users/jfgonzalezm/VSCProjects/my-config-api/pyproject.toml: Key "fastapi-users" already exists.

### ISSUE THREAD

**Issue by concongo** [Tobi-De/cookiecutter-fastapi#2]
When using `beanie` as ODM, a second `fastapi-users` dependencie is created, then running `poetry export -f requirements.txt --output requirements.txt --without-hashes` locally produces the mentioned error.

**Comment by Tobi-De** [comment]
Thanks for reporting @concongo , has been fixed.
